# Generated by Django 2.2.6 on 2022-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220521_2318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follower'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='Follow',
        ),
    ]
